[Settings]
ID = 'readermo.de'

[build]
command = 'npm run export'
publish = '__sapper__/export'
functions = './functions'

# Redirect every route to index and let Sapper handle it
[[redirects]]
from="/*"
to="index.html"
status=200
