[Settings]
ID = 'readermo.de'

[build]
command = 'npm run build'
publish = '__sapper__/export'
functions = 'functions'

[dev]
command = 'npm run dev'
port = 3000

# Redirect every route to index and let Sapper handle it
[[redirects]]
from="/*"
to="index.html"
status=200
